
export const RETRIEVE_EMPS = "RETRIEVE_EMPS";
export const RETRIEVE_EMPS_BY_FIRST_NAME = "RETRIEVE_EMPS_BY_FIRST_NAME";
export const EMPS_RECEIVED = "EMPS_RECEIVED";
export const CREATE_EMP = "CREATE_EMP";
export const UPDATE_EMP = "UPDATE_EMP";
export const DELETE_EMP = "DELETE_EMP";
export const DELETE_ALL_EMPS = "DELETE_ALL_EMPS";

export const CREATE_EMP_SUCCESS_FULL = "";
export const UPDATE_EMP_SUCCESS_FULL = "";
export const DELETE_EMP_SUCCESS_FULL = "";

export const CREATE_EMP_FAILED = "CREATE_EMP_FAILED";
export const UPDATE_EMP_FAILED = "UPDATE_EMP_FAILED";
export const DELETE_EMP_FAILED = "DELETE_EMP_FAILED";
export const RETRIEVE_EMPS_FAILED ="RETRIEVE_EMPS_FAILED";

